name: DL-tf
channels:
  - apple
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - aiohttp=3.8.4=py38hb991d35_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.7.1=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38hb192615_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-lru=1.0.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotlipy=0.7.0=py38hb991d35_1005
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2024.2.2=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.1=py38ha45ccd6_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.1.1=py38h9afee92_1
  - cryptography=40.0.2=py38h23f6d3d_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.1=py38hb9fa5a8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - fonttools=4.51.0=py38h336bac9_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hadb7bae_2
  - frozenlist=1.3.3=py38hb991d35_0
  - gast=0.4.0=pyh9f0ad1d_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.51.1=py38h9dcc83b_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.6.0=nompi_py38hacf61ce_100
  - hdf5=1.12.1=nompi_hd9dbc9e_104
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.5.1=pyha770c72_0
  - importlib-resources=6.4.0=pyhd8ed1ab_0
  - importlib_metadata=6.5.1=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.12.2=pyhd1c38e8_0
  - ipywidgets=8.1.2=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.4.0=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=2.4=py38h10201cd_3
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.22.0=pyhd8ed1ab_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py38h10201cd_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.7.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.1.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.24.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.10=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py38h9afee92_1
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.15=h40e5a24_2
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20220623.0=cxx17_h28b99d4_6
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=8.4.0=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.19=hb547adb_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=12_2_0_hd922786_31
  - libgfortran5=12.2.0=h0eea778_31
  - libgrpc=1.51.1=h55edf5b_0
  - libjpeg-turbo=2.1.5.1=hb547adb_1
  - liblapack=3.9.0=16_osxarm64_openblas
  - libllvm11=11.1.0=hfa12f05_5
  - libnghttp2=1.52.0=hae82a92_0
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.43=h091b4b1_0
  - libprotobuf=3.21.12=hb5ab8b9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtiff=4.6.0=h77c4dce_1
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.15=hf346824_0
  - libxgboost=2.0.3=cpu_h6db52da_4
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=18.1.3=hcd81f8e_0
  - markdown=3.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.2=py38hb991d35_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - multidict=6.0.4=py38hb991d35_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.4=hd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_0
  - nbconvert-pandoc=7.16.4=hd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook=7.1.3=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=1.22.4=py38he1fcd3f_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.3.0=hfb2fe0b_3
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandoc=3.1.13=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py38hf19b724_1
  - pip=23.1.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - psutil=5.9.8=py38h336bac9_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-xgboost=2.0.3=cpu_pyh995e691_4
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.16=h3ba56d0_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.8=3_cp38
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py38hb192615_1
  - pyzmq=26.0.2=py38h1347feb_0
  - qtconsole-base=5.5.1=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - re2=2022.06.01=h9a09cb3_1
  - readline=8.2=h92ec313_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.28.2=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.18.0=py38h4424ae1_0
  - rsa=4.9=pyhd8ed1ab_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=67.7.1=pyhd8ed1ab_0
  - six=1.15.0=pyh9f0ad1d_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py38hd97cf01_0
  - tensorboard-data-server=0.6.1=py38h23f6d3d_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow-deps=2.9.0=0
  - termcolor=1.1.0=pyhd8ed1ab_3
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4=py38h336bac9_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - unicodedata2=15.1.0=py38hb192615_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=4.0.10=pyhd8ed1ab_0
  - wrapt=1.12.1=py38hea4295b_3
  - xgboost=2.0.3=cpu_pyhb8f9a19_4
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.8.2=py38hb991d35_0
  - zeromq=4.3.5=hebf3989_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - absl-py==2.1.0
      - category-encoders==2.6.3
      - cloudpickle==3.0.0
      - cython==3.0.10
      - dash==2.17.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - deprecated==1.2.14
      - deprecation==2.1.0
      - docker-pycreds==0.4.0
      - flask==3.0.3
      - flatbuffers==1.12
      - gitdb==4.0.11
      - gitpython==3.1.43
      - imbalanced-learn==0.12.3
      - itsdangerous==2.2.0
      - kaggle==1.6.14
      - kaleido==0.2.1
      - keras==2.9.0
      - keras-tuner==1.4.7
      - kt-legacy==1.0.5
      - libclang==18.1.1
      - lightgbm==4.3.0
      - llvmlite==0.41.1
      - matplotlib==3.6.0
      - numba==0.58.1
      - orjson==3.10.3
      - pandas==1.5.3
      - plotly==5.22.0
      - plotly-resampler==0.10.0
      - pmdarima==2.0.4
      - protobuf==3.19.6
      - pydot==2.0.0
      - pyod==1.1.3
      - python-graphviz==0.20.3
      - python-slugify==8.0.4
      - retrying==1.3.4
      - schemdraw==0.15
      - scikit-base==0.5.2
      - scikit-learn==1.2.2
      - scikit-plot==0.3.7
      - scipy==1.10.1
      - sentry-sdk==2.5.1
      - setproctitle==1.3.3
      - sktime==0.21.1
      - smmap==5.0.1
      - tbats==1.1.3
      - tenacity==8.3.0
      - tensorboard==2.9.1
      - tensorflow-estimator==2.9.0
      - tensorflow-macos==2.9.0
      - tensorflow-metal==0.5.0
      - text-unidecode==1.3
      - tqdm==4.66.4
      - tsdownsample==0.1.3
      - typing-extensions==4.12.0
      - wandb==0.17.1
      - werkzeug==3.0.3
      - wget==3.2
      - wurlitzer==3.1.0
      - xxhash==3.4.1
      - yellowbrick==1.5
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/DL-tf
